### ISSUE TITLE
Issue access carQuery API from frontend

### ISSUE THREAD

**Issue by SamWalker7** [jtlwheeler/CarQuery#7]
# Issue
import {CarQuery} from 'car-query';
 useEffect(() => {
    carQuery.getYears().then(years => console.log('years: ' + years)).catch(e => console.log('error: ' + e));
  }, []);

Error: CORS error

Accessing the carQuery API from frontend returns a cors error. I've tried using axios/fetch to call the url 'https://www.carqueryapi.com/api/0.3/?callback=?&cmd=getModels'. I've also tried installing the npmjs packing as above.

**Comment by jtlwheeler** [comment]
Please see the [Known Issues section](https://github.com/jtlwheeler/CarQuery?tab=readme-ov-file#known-issues). I'm not the maintainer of the CarQuery REST API, so I'm unable to address this issue.
